version: '3.8'

services:
  teslo-shop:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestStarter
    container_name: NestStarter
    env_file:
      - .env
    ports:
      - "4301:5432"
    volumes:
       - ./postgres:/var/lib/postgresql/data
    
    
